clean:
	-del -f *.exe
	
all:  test ArrayReverse LinkList

test: test.cpp
	g++ -std=c++2a -o test test.cpp

ArrayReverse: ArrayReverse.cpp
	g++ -std=c++2a -o ArrayReverse ArrayReverse.cpp

LinkList: LinkList.cpp
	g++ -std=c++2a -o LinkList LinkList.cpp